import type { Metadata } from "next";
import { Manrope } from 'next/font/google';
import Navbar from './components/Navbar/Navbar';
import { Footer } from "./components/Footer/Footer";

import "./globals.css";

const inter = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} transition-all duration-300`}>
      <Navbar />
      {children}
      <Footer />
      </body>
    </html>
  );
}
